package hlam.newWindow1;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 * User: Vova
 * Date: 30.10.12
 * Time: 23:49
 */
public class MainWindow1 {
    private JPanel rootPanel;
    private JTabbedPane tabbedPane1;
    private JTabbedPane tabbedPane2;
    private JCheckBox splitedCheckBox;
    private JSplitPane splitPane;

    public MainWindow1() {
        $$$setupUI$$$();
        splitedCheckBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (splitedCheckBox.isSelected()) {
                    splitPane.setDividerLocation(rootPanel.getWidth() / 2);
                    tabbedPane1.addTab(tabbedPane2.getTitleAt(0), null);
                    tabbedPane2.removeTabAt(0);
                    tabbedPane1.addTab(tabbedPane2.getTitleAt(0), null);
                    tabbedPane2.removeTabAt(0);
//                    ((JTabbedPaneCustom)tabbedPane2).moveAll();
                } else {
                    splitPane.setDividerLocation(0);
                    ((JTabbedPaneCustom) tabbedPane1).moveAll();
//                    for (int i = 0; i <= tabbedPane1.getTabCount(); i++) {
//                        tabbedPane2.addTab(tabbedPane1.getTitleAt(0), tabbedPane1.getTabComponentAt(0));
//                        tabbedPane1.remove(0);
//                    }

                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MainWindow1");
        final MainWindow1 mainWindow1 = new MainWindow1();
        mainWindow1.tabbedPane1.setTitleAt(0, "first");
        mainWindow1.tabbedPane1.setTitleAt(1, "second");
        mainWindow1.tabbedPane2.setTitleAt(0, "third");
        mainWindow1.tabbedPane2.setTitleAt(1, "fourth");
        System.out.println(mainWindow1.tabbedPane1.getTabComponentAt(0));
        frame.setContentPane(mainWindow1.rootPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        mainWindow1.rootPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                if (mainWindow1.splitedCheckBox.isSelected())
                    mainWindow1.splitPane.setDividerLocation(mainWindow1.rootPanel.getWidth() / 2);
            }
        });
    }

    private void createUIComponents() {
        JTabbedPaneCustom jTabbedPaneCustom1 = new JTabbedPaneCustom("\u25ba");
        JTabbedPaneCustom jTabbedPaneCustom2 = new JTabbedPaneCustom("\u25c4");

        jTabbedPaneCustom1.setAnother(jTabbedPaneCustom2);
        jTabbedPaneCustom2.setAnother(jTabbedPaneCustom1);

        tabbedPane1 = jTabbedPaneCustom1;
        tabbedPane2 = jTabbedPaneCustom2;

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setBackground(new Color(-9071731));
        toolBar1.setBorderPainted(true);
        toolBar1.setEnabled(true);
        toolBar1.setFloatable(false);
        toolBar1.putClientProperty("html.disable", Boolean.FALSE);
        rootPanel.add(toolBar1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 25), new Dimension(-1, 25), null, 0, false));
        splitedCheckBox = new JCheckBox();
        splitedCheckBox.setBackground(new Color(-9071731));
        splitedCheckBox.setEnabled(true);
        splitedCheckBox.setForeground(new Color(-205));
        splitedCheckBox.setHideActionText(true);
        splitedCheckBox.setSelected(true);
        splitedCheckBox.setText("Splited");
        toolBar1.add(splitedCheckBox);
        splitPane = new JSplitPane();
        splitPane.setContinuousLayout(false);
        splitPane.setDividerLocation(496);
        splitPane.setDividerSize(2);
        splitPane.setEnabled(false);
        rootPanel.add(splitPane, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(1000, 0), new Dimension(200, 650), null, 0, false));
        tabbedPane1.setTabLayoutPolicy(0);
        tabbedPane1.setTabPlacement(3);
        splitPane.setLeftComponent(tabbedPane1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Untitled", panel1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Untitled", panel2);
        tabbedPane2.setTabPlacement(3);
        splitPane.setRightComponent(tabbedPane2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane2.addTab("Untitled", panel3);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane2.addTab("Untitled", panel4);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
